Building DAG of jobs...
Using shell: /usr/local/bin/bash
Provided cores: 96
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Tue Aug  2 01:04:33 2022]
rule run_pangolin:
    input: /hps/nobackup/cochrane/ena/users/azyoud/lineages_workflow_output/public_consensus_workflow_output/public_multifasta/multifasta_281.fasta
    output: /hps/nobackup/cochrane/ena/users/azyoud/lineages_workflow_output/public_consensus_workflow_output/pango/pango_lineages.281.csv
    jobid: 0
    wildcards: n=281
    threads: 4
    resources: mem_mb=2048, disk_mb=1000, tmpdir=/nfs/production/cochrane/ena/users/azyoud

Job stats:
job                      count    min threads    max threads
---------------------  -------  -------------  -------------
align_to_reference           1              1              1
all                          1              1              1
cache_sequence_assign        1              1              1
create_seq_hash              1              1              1
get_constellations           1              1              1
merged_info                  1              1              1
scorpio                      1              4              4
sequence_qc                  1              1              1
total                        8              1              4

[32m[Tue Aug  2 01:04:50 2022][0m
[31mError in rule align_to_reference:[0m
[31m    jobid: 0[0m
[31m    output: /nfs/production/cochrane/ena/users/azyoud/tmpyscj8st8/alignment.fasta[0m
[31m    log: /nfs/production/cochrane/ena/users/azyoud/tmpyscj8st8/logs/minimap2_sam.log (check log file(s) for error message)[0m
[31m[0m
[31mRuleException:
CalledProcessError in line 54 of /nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/preprocessing.smk:
Command 'set -euo pipefail;  cat "/hps/nobackup/cochrane/ena/users/azyoud/lineages_workflow_output/public_consensus_workflow_output/public_multifasta/multifasta_281.fasta" | awk '{ if ($0 !~ /^>/) { gsub("-", "",$0); } print $0; }'   |             awk '{ { gsub(" ", "_",$0); } { gsub(",", "_",$0); } print $0; }'  |             minimap2 -a -x asm20 --sam-hit-only --secondary=no --score-N=0  -t  4 /nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/site-packages/pangolin/data/reference.fasta - -o /nfs/production/cochrane/ena/users/azyoud/tmpyscj8st8/mapped.sam &> /nfs/production/cochrane/ena/users/azyoud/tmpyscj8st8/logs/minimap2_sam.log 
            gofasta sam toMultiAlign                 -s /nfs/production/cochrane/ena/users/azyoud/tmpyscj8st8/mapped.sam                 -t 4                 --reference /nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/site-packages/pangolin/data/reference.fasta                 --trimstart 265                 --trimend 29674                 --trim                 --pad > '/nfs/production/cochrane/ena/users/azyoud/tmpyscj8st8/alignment.fasta'' died with <Signals.SIGINT: 2>.
  File "/nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/preprocessing.smk", line 54, in __rule_align_to_reference
  File "/nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/concurrent/futures/thread.py", line 57, in run[0m
Traceback (most recent call last):
  File "/nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/threading.py", line 433, in acquire
    self._cond.wait(timeout)
  File "/nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/site-packages/snakemake/workflow.py", line 1060, in execute
    success = self.scheduler.schedule()
  File "/nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/site-packages/snakemake/scheduler.py", line 438, in schedule
    self._open_jobs.acquire()
  File "/nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/threading.py", line 436, in acquire
    rc = True
  File "/nfs/production/cochrane/ena/users/azyoud/miniconda/envs/pangolin/lib/python3.8/threading.py", line 250, in __exit__
    return self._lock.__exit__(*args)
RuntimeError: release unlocked lock
[Tue Aug  2 01:04:50 2022]
Error in rule run_pangolin:
    jobid: 0
    output: /hps/nobackup/cochrane/ena/users/azyoud/lineages_workflow_output/public_consensus_workflow_output/pango/pango_lineages.281.csv
    shell:
        pangolin --threads 4 --outfile /hps/nobackup/cochrane/ena/users/azyoud/lineages_workflow_output/public_consensus_workflow_output/pango/pango_lineages.281.csv /hps/nobackup/cochrane/ena/users/azyoud/lineages_workflow_output/public_consensus_workflow_output/public_multifasta/multifasta_281.fasta
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

